### ISSUE TITLE
[Request] Option to disable factions colors on specific tokens

### ISSUE THREAD

**Issue by Sky-Captain-13** [Voldemalort/token-factions#10]
I use tokens on some maps to represent points of interest or something other than a creature/enemy/etc. Token Tooltip has an option to disable tooltips. Would be cool to have one for faction bases too.

![image](https://user-images.githubusercontent.com/10356477/100491216-d55eaa00-30ef-11eb-8f98-f24aa14cae1b.png)

**Comment by Voldemalort** [comment]
closing as this is a repeat of https://github.com/Voldemalort/token-factions/issues/8 and can be accomplished through folders (see resolution of #8
