### ISSUE TITLE
Enhancement: Ability to customize the size of the overlay.

### ISSUE THREAD

**Issue by Ikabodo** [Voldemalort/token-factions#4]
Depending on the type of token used, the graphic might be too easy or too hard to see.
It would be useful to be able to change the width of the border visible.

**Comment by Voldemalort** [comment]
Opinionated: I'd rather not have too many per-token settings, but I could see exposing this as a global setting

**Comment by Voldemalort** [comment]
I decided to implement this in the most recent release
