### ISSUE TITLE
Enhancement: Small and tiny token support. 

### ISSUE THREAD

**Issue by Ikabodo** [Voldemalort/token-factions#5]
If the token is small, the overlay becomes a little to visible.

**Comment by Ikabodo** [comment]
![image](https://user-images.githubusercontent.com/7766890/99980478-94d9f600-2da8-11eb-8314-fb0bbe3cd134.png)

**Comment by Voldemalort** [comment]
I'll look into this, but I think different people handle tiny tokens differently - either with a full unit image and changing the token scale, or leaving the token as one unit but centering a smaller image - I can't accommodate both easily

**Comment by Ikabodo** [comment]
Understandable. I thought most people used the scale since it's so readily available.

**Comment by Voldemalort** [comment]
I'll look closer at the issue, I just know there are modules to "fix" tiny creatures which would imply the built-ins aren't used by everyone. I'll start by looking at that mod to see what it does

**Comment by Voldemalort** [comment]
closing this as this is mostly understanding how to use scale and sizing.
