### ISSUE TITLE
Enhancement: Global opacity option

### ISSUE THREAD

**Issue by amcvfx** [Voldemalort/token-factions#9]
I use top down tokens and this module works wonders helping them stand out on maps where they aren't clear. But the fully opaque circle is actually a bit strong and I was wondering if an opacity option could be added to affect all the tokens (the ring and the fill)? I could then dial in exactly how strong the faction circle appears so it can be a more subtle effect.

**Comment by Voldemalort** [comment]
Seems reasonable. I'll see if it's easy to do.

**Comment by Voldemalort** [comment]
working on this

**Comment by Voldemalort** [comment]
just released
